language: node_js
dist: xenial
sudo: required
addons:
  apt:
    packages:
      - libnss3
      - google-chrome-stable
env:
  global:
    - GOOGLE_CHROME_BINARY="/usr/bin/google-chrome-stable"
    - PUPPETEER_SKIP_CHROMIUM_DOWNLOAD="true"
node_js:
  - "8"
  - "10"
  - "12"
before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH="$HOME/.yarn/bin:$PATH"
install: yarn --frozen-lockfile
script:
  - node --version
  - yarn --version
  - yarn build:ci
  - yarn test
notifications:
  email:
    on_failure: change
cache:
  yarn: true
  directories:
    - node_modules
