name: Publish GitHub release
description: Publishes a new release on GitHub, with the given changelog and tag

inputs:
  tag:
    description: The tag name
    required: true
  changelog:
    description: The new changelog
    required: true
  token:
    description: A GitHub access token
    required: true
  is-tag-stable:
    description: Specifies whether release is a prerelease or not
    required: true
    default: 'false'

runs:
  using: node12
  main: main.js
