name: Deploy Dev

on:
  push:
    branches:
      - dev

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master
      - name: Use Node.js 10.x
        uses: actions/setup-node@v1
        with:
          version: 10.x
      - name: Installs yarn
        run: npm i -g yarn
      - name: yarn install and build and test
        run: |
          yarn
          yarn build:action
          yarn test
      - name: test
        run: yarn test
      - name: deploy
        uses: actions/zeit-now@master
        env:
          ZEIT_TOKEN: ${{secrets.ZEIT_TOKEN}}
        args: deploy  --no-clipboard  packages/storybook --scope react-hooks > $HOME/deploy.txt
