name: Version bump

on:
  push:
    tags: ["v*"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the tag
        uses: actions/checkout@v1.0.0
      - name: Get tag info
        id: tags
        uses: ./.github/actions/get-release-tags
      - name: Generate the changelog
        id: changelog
        uses: ./.github/actions/generate-lerna-changelog
        with:
          from: ${{ steps.tags.outputs.old }}
          to: ${{ steps.tags.outputs.new }}
        env:
          GITHUB_AUTH: ${{ secrets.GITHUB_TOKEN }}
      - name: Create a draft GitHub release
        uses: ./.github/actions/publish-github-release
        with:
          tag: ${{ steps.tags.outputs.new }}
          changelog: ${{ steps.changelog.outputs.changelog }}
          token: ${{ secrets.BOT_TOKEN }}
      - name: Check if releasing from master
        id: is_master
        uses: ./.github/actions/ref-matches-branch
        with:
          name: master
      - name: Generate docusaurus
        if: steps.is_master.outputs.result == 1
        run: yarn run readme-to-docs
      - name: Build docusaurus
        if: steps.is_master.outputs.result == 1
        run:  cd packages/docusaurus && yarn build
      - name: Version docusaurus
        if: steps.is_master.outputs.result == 1
        run:  cd packages/docusaurus && yarn run docs-version ${{steps.latestTag.outputs.latest}}
      - name: Commit docusaurus
        if: steps.is_master.outputs.result == 1
        run: |
          git add packages/docusaurus
          git -c user.name="imbhargav5" -c user.email="imbhargav5@users.noreply.github.com" \
            commit -m "Update ${{ steps.tags.outputs.new }} docusaurus [skip ci]" --no-verify --quiet
          git push "https://imbhargav5:${{ secrets.GITHUB_TOKEN }}@github.com/${GITHUB_REPOSITORY}.git" master
      - name: Deploy docusaurus
        if: steps.is_master.outputs.result == 1
        run: cd packages/docusaurus && yarn run deploy --token $ZEIT_TOKEN      
      - name: Update CHANGELOG.md
        if: steps.is_master.outputs.result == 1
        uses: ./.github/actions/update-changelog
        with:
          changelog: ${{ steps.changelog.outputs.changelog }}
      - name: Commit CHANGELOG.md
        if: steps.is_master.outputs.result == 1
        run: |
          git add CHANGELOG.md
          git -c user.name="imbhargav5" -c user.email="imbhargav5@users.noreply.github.com" \
            commit -m "Add ${{ steps.tags.outputs.new }} to CHANGELOG.md [skip ci]" --no-verify --quiet
          git push "https://imbhargav5:${{ secrets.GITHUB_TOKEN }}@github.com/${GITHUB_REPOSITORY}.git" master
